# run: conda env create --file environment.yaml
name: datta_notebook_env
channels:
    - conda-forge
dependencies:
    - python==3.10
    - ipywidgets
    - pip
    - pip:
      - cellpose==1.0.2
      - scikit-image
      - imagecodecs
      - ipykernel
      - seaborn
      - matplotlib
      - tqdm
      - toml
      - datta-lab-to-nwb @ git+https://github.com/catalystneuro/datta-lab-to-nwb.git@main
