name: bcm-workshop
channels:
  - defaults
dependencies:
  - python=3.12
  - pip=23.3.1
  - pip:
      - aiohttp==3.9.4
      - dandi==0.61.2
      - fsspec==2024.3.1
      - jupyterlab==4.1.6
      - matplotlib==3.8.4
      - pynapple==0.6.2
      - pynwb==2.6.0
      - requests==2.31.0
      - seaborn==0.13.2
