# run: conda env create --file environment.yaml
# activate: conda activate 000458_fi
# update: conda env update --file environment.yaml --prune
name: 000458_fi
channels:
    - conda-forge
dependencies:
    - python==3.12
    - pip
    - pip:
      - dandi==0.63.0
      - pynwb==2.8.1
      - ipykernel==6.29.5
      - matplotlib==3.9.2
      - lindi==0.4.0a1
      - fsspec==2024.6.1